package.json, persistence.js
It's easy for [QlobberSub](https://github.com/davedoesdev/qlobber/blob/master/aedes/qlobber-sub.js) to do and is O(1). Makes negligible different to the [aedes bench](https://github.com/davedoesdev/qlobber/blob/master/aedes/bench/sub.js) results. 
[Tested](https://github.com/davedoesdev/qlobber/blob/master/test/aedes.js) to 100% coverage of QlobberSub.
This is useful for aedes-persistence-redis so it doesn't have to jump through hoops to maintain an offline subscription count (which it actually fails to do correctly at the moment).
=> Count offline subscriptions in QlobberSub

abstract.js, package.json, persistence.js
The callback like `emptyQueueFilter` in https://github.com/mcollina/aedes/blob/master/lib/handlers/connect.js#L178, and this will not fail the unit test in https://github.com/mcollina/aedes/blob/master/test/client-pub-sub.js#L114
=> Allow callback for non-publish packet in outgoingUpdate

abstract.js
When storing docs with mongodb, if a key has an undefined value that will be converted to null when stored and this makes test fails.
This PR paired with another on aedes-persistence-mongodb that deletes undefined messageIds before storing a doc will fix the tests.
There is still one test that is failing but I need your help:
```
⨯ add outgoing packet as a string and pump
not ok 225 should be equal
---
operator: equal
expected: 2
actual:   0
at: done (/aedes-persistence/abstract.js:888:13)
```
=> Fixing failing tests with aedes-persistence-mongodb

abstract.js, persistence.js, test.js
This rule is on its way into the latest Standard ☺️
ref: https://github.com/standard/eslint-config-standard/pull/166
Compatibility: This syntax is supported in Node.js 4.x and up, and this module declares compatibility with Node.js 10.x and up ✅
=> Use object shorthand for properties

abstract.js
See [aedes-persistence-mongodb#65](https://github.com/moscajs/aedes-persistence-mongodb/pull/65)
=> fix: Abstract topic list concurrency failing due to result ordering

abstract.js, package.json, persistence.js
This PR updates all dependencies to the most current version
It also adds `@types/node` as `npm test` failed because of this module missing.
As Standard 16 is more strict than Standard 15 I also applied `standard --fix` hence the changes to persistence.js and abstract.js
No manual edits have been applied.
My plan is to do modernization (like the one done on aedes-persistence-level) in a seperate PR after this PR has been merged so I can start at a current version.
Kind regards,
Hans
=> chore: update dependencies 

.github/workflows/ci.yml, README.md, abstract.js, package.json, persistence.js, types/index.d.ts
Items on the shopping list I hope to achieve in this PR:
-  [X] Migrate from ES5 classes to ES6 classes
-  [X] other ES5 to ES6 optimizations
-  [X] replace internal use of third party streams by generators/Node native streams where possible
-  [X] Migrate from ES5 classes to ES6 classes
-  [X] other ES5 to ES6 optimizations
-  [X] replace internal use of third party streams by generators/Node native streams where possible
All while maintaining the abstract interface, hence the two step approach so we can't accidentally mess up either of them ;-)
If I missed anything just let me know.
I created this as a draft PR so you can follow along.
Kind regards,
Hans
=> chore: es5 to es6, drop nodejs 12

package.json, persistence.js, types/index.d.ts
Standardjs 17 has just been released and now supports ECMA script standard [private class features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) (starting with '#')
This PR updates the dependency and updates the code to use ECMA script standard private class members.
Kind regards,
Hans
=> chore: upgrade to standardjs@17 and private class members

abstract.js
This PR fixes the race conditions encountered while trying get `aedes-persistence-level` to work with version 9.0.1
`aedes-persistence-level` tested succesfully with these patches applied to abstract.js.
Kind regards,
Hans
=> fix: fix race conditions in abstract.js

abstract.js
This PR fixes the following issues found in https://github.com/moscajs/aedes-persistence-level/pull/31:
- unstable legacy stream support which caused tests in that PR to fail on NodeJS 16 and to throw on NodeJS 18
- changed behaviour of `deepEqual` between `tape 4.x` and `tape-5.x` which caused plain objects (`{ cmd: 'publish', brokerId: 'broker-42',...`) to be unequal to bound objects ( `Packet { cmd: 'publish', brokerId: 'broker-42',...`) in testing `aedes-persistence-level`
Persistence providers that rely on legacy streams (e.g. `From2`) will need to provide an option as specified in README.md to make tests succeed. 
As usual: comments/feedback/change requests are all appreciated.
Kind regards,
Hans
=> fix: legacy stream support and classless compare

abstract.js, package.json, persistence.js
Hi,
I am working on fixing Aedes bridge connection where `nl` flag is not respected:
https://github.com/moscajs/aedes/issues/736
For that I need to update `aedes-persistence` to persist `nl`, `rap` and `rh` flags.
The tests are still failing because `qlobber` also needs to be updated to work with `nl`, `rap` and `rh` flags:
https://github.com/davedoesdev/qlobber/pull/24
So this pull request needs to wait until qlobber is updated. 👍
=> feat: persist rh, rap, nl

abstract.js
This PR adds missing brokerId's to abstract.js as found while researching https://github.com/moscajs/aedes-persistence-redis/issues/98
Kind regards,
Hans
=> fix: unknown brokerId's during testing

.github/workflows/ci.yml, abstract.js, eslint.config.js, package.json, test.js
This PR:
-  updates CI to use recent node versions
-  replaces `standard` by `eslint` with `neostandard`
-  replaces `pre-commit` by `@fastify/pre-commit`
-  replace `tape` and `faucet` by `node:test` 
-  upgrades all other dependencies to their latest versions
Kind regards,
Hans
=> chore: upgrade dependencies

README.md
https://david-dm.org/moscajs/aedes-persistence/dev-status.svg 
and 
https://david-dm.org/moscajs/aedes-persistence/status.svg 
don't produce badges anymore.
Removing them from the README.md avoids potential future security issues.
Kind regards,
Hans
=> docs: remove defunct badges from README.md

test.js
as discussed in #95 this PR adds 'waitForReady:true` to the asyncMemory test.
=> fix: add waitForReady to asyncMemory test

abstract.js
This PR fixes a bug that I found whlle working on `aedes-persistence-mongodb`. I learned that when using `aedes-cached-persistence` (which builds on `aedes-persistense`) calls the  `_setup` method of the persistence as soon as `instance.broker`  is set. And as `_setup` emits the `ready` event, waiting for this event in `abstract.js` can only happen after setting `instance.broker` or else the wait will be forever.
This only touches `abstract.js` which is only used during testing of the various persistences.
Kind regards,
Hans
=> fix:  fix waitForReady

abstract.js, package.json, promisified.js
This PR takes the promisified versions of the persistence interface and puts them into `promisified.js` .
This enables other persistencies (e.g.  mongodb, redis etc) to import these functions and use them in their own testing, saving double maintenance.
Kind regards,
Hans
=> feature: externalize promisified versions of the persistence interface

abstract.js, promisified.js
as requested in: https://github.com/moscajs/aedes-persistence-mongodb/pull/83
Kind regards,
Hans
=> fix: replace waitForEvent() by once()

abstract.js
This PR adds additional patterns with multiple wildcards to match on retained messages to the test suite in abstract.js
It aims to prevent regressions on https://github.com/moscajs/aedes-persistence-redis/pull/123
Kind regards,
Hans
=> feat: add additional retained match patterns with multiple wildcards to abstract.js

abstract.js, callBackPersistence.js
while migrating aedes to async persistence I noticed that the `setup()` call in callback persistence did not return a promise.
This PR fixes that.
Kind regards,
Hans
=> fix: make setup() in callBackPersistence async
